import { QRTypeConfig } from '@/types/qr.types'

export const QR_TYPES: QRTypeConfig[] = [
  {
    id: 'url',
    label: 'URL',
    icon: '🌐',
    description: 'Link to any website',
    color: '#66cc99',
  },
  {
    id: 'text',
    label: 'Text',
    icon: '📝',
    description: 'Plain text message',
    color: '#5b9bd5',
  },
  {
    id: 'email',
    label: 'Email',
    icon: '✉️',
    description: 'Send an email',
    color: '#e8734a',
  },
  {
    id: 'phone',
    label: 'Phone',
    icon: '📞',
    description: 'Dial a phone number',
    color: '#66cc99',
  },
  {
    id: 'sms',
    label: 'SMS',
    icon: '💬',
    description: 'Send a text message',
    color: '#a78bfa',
  },
  {
    id: 'vcard',
    label: 'vCard',
    icon: '👤',
    description: 'Share contact info',
    color: '#f59e0b',
  },
  {
    id: 'wifi',
    label: 'WiFi',
    icon: '📶',
    description: 'Connect to WiFi',
    color: '#06b6d4',
  },
  {
    id: 'location',
    label: 'Location',
    icon: '📍',
    description: 'Share a map location',
    color: '#ef4444',
  },
  {
    id: 'facebook',
    label: 'Facebook',
    icon: '📘',
    description: 'Facebook profile/page',
    color: '#1877f2',
  },
  {
    id: 'twitter',
    label: 'Twitter / X',
    icon: '🐦',
    description: 'Twitter/X profile',
    color: '#1da1f2',
  },
  {
    id: 'instagram',
    label: 'Instagram',
    icon: '📸',
    description: 'Instagram profile',
    color: '#e1306c',
  },
  {
    id: 'youtube',
    label: 'YouTube',
    icon: '▶️',
    description: 'YouTube channel/video',
    color: '#ff0000',
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    icon: '💚',
    description: 'WhatsApp message',
    color: '#25d366',
  },
  {
    id: 'event',
    label: 'Event',
    icon: '📅',
    description: 'Calendar event',
    color: '#8b5cf6',
  },
  {
    id: 'payment',
    label: 'Payment',
    icon: '💳',
    description: 'Payment link',
    color: '#f59e0b',
  },
]

export const DEFAULT_CUSTOMIZATION = {
  foregroundColor: '#0f1923',
  backgroundColor: '#ffffff',
  dotType: 'rounded' as const,
  cornerSquareType: 'extra-rounded' as const,
  cornerDotType: 'dot' as const,
  logoUrl: null,
  logoSize: 0.3,
  logoMargin: 5,
  frameStyle: 'none' as const,
  frameColor: '#66cc99',
  frameLabel: 'SCAN ME',
  size: 400,
  errorCorrectionLevel: 'M' as const,
}